-- begin TICKET_LINE_PERSON
alter table TICKET_LINE_PERSON add constraint FK_TICKET_LINE_PERSON_ON_PERSON foreign key (PERSON_ID) references TICKET_PERSON(ID)^
alter table TICKET_LINE_PERSON add constraint FK_TICKET_LINE_PERSON_ON_ISSUE foreign key (ISSUE_ID) references TICKET_ISSUE(ID)^
alter table TICKET_LINE_PERSON add constraint FK_TICKET_LINE_PERSON_ON_TICKET_ISSUE foreign key (TICKET_ISSUE_ID) references TICKET_TICKET_ISSUE(ID)^
alter table TICKET_LINE_PERSON add constraint FK_TICKET_LINE_PERSON_ON_TICKET_WITHDRAWAL foreign key (TICKET_WITHDRAWAL_ID) references TICKET_TICKET_WITHDRAWAL(ID)^
create index IDX_TICKET_LINE_PERSON_ON_PERSON on TICKET_LINE_PERSON (PERSON_ID)^
create index IDX_TICKET_LINE_PERSON_ON_ISSUE on TICKET_LINE_PERSON (ISSUE_ID)^
create index IDX_TICKET_LINE_PERSON_ON_TICKET_ISSUE on TICKET_LINE_PERSON (TICKET_ISSUE_ID)^
create index IDX_TICKET_LINE_PERSON_ON_TICKET_WITHDRAWAL on TICKET_LINE_PERSON (TICKET_WITHDRAWAL_ID)^
-- end TICKET_LINE_PERSON
-- begin TICKET_LINE_TICKET
alter table TICKET_LINE_TICKET add constraint FK_TICKET_LINE_TICKET_ON_TICKET foreign key (TICKET_ID) references TICKET_TICKET(ID)^
alter table TICKET_LINE_TICKET add constraint FK_TICKET_LINE_TICKET_ON_LINE_PERSON foreign key (LINE_PERSON_ID) references TICKET_LINE_PERSON(ID)^
create index IDX_TICKET_LINE_TICKET_ON_TICKET on TICKET_LINE_TICKET (TICKET_ID)^
create index IDX_TICKET_LINE_TICKET_ON_LINE_PERSON on TICKET_LINE_TICKET (LINE_PERSON_ID)^
-- end TICKET_LINE_TICKET

-- begin TICKET_ISSUE
alter table TICKET_ISSUE add constraint FK_TICKET_ISSUE_ON_RELATIVE_DOCS foreign key (RELATIVE_DOCS_ID) references TICKET_INCIDENT(ID)^
alter table TICKET_ISSUE add constraint FK_TICKET_ISSUE_ON_ISSUE_PATTERN foreign key (ISSUE_PATTERN_ID) references TICKET_PATTERN(ID)^
create index IDX_TICKET_ISSUE_ON_RELATIVE_DOCS on TICKET_ISSUE (RELATIVE_DOCS_ID)^
create index IDX_TICKET_ISSUE_ON_ISSUE_PATTERN on TICKET_ISSUE (ISSUE_PATTERN_ID)^
-- end TICKET_ISSUE
-- begin TICKET_LINE_SHAPE
alter table TICKET_LINE_SHAPE add constraint FK_TICKET_LINE_SHAPE_ON_PATTERN foreign key (PATTERN_ID) references TICKET_PATTERN(ID)^
create index IDX_TICKET_LINE_SHAPE_ON_PATTERN on TICKET_LINE_SHAPE (PATTERN_ID)^
-- end TICKET_LINE_SHAPE
-- begin TICKET_LINE_TICKET_REGISTER
alter table TICKET_LINE_TICKET_REGISTER add constraint FK_TICKET_LINE_TICKET_REGISTER_ON_TICKET foreign key (TICKET_ID) references TICKET_TICKET(ID)^
alter table TICKET_LINE_TICKET_REGISTER add constraint FK_TICKET_LINE_TICKET_REGISTER_ON_PERSON foreign key (PERSON_ID) references TICKET_PERSON(ID)^
alter table TICKET_LINE_TICKET_REGISTER add constraint FK_TICKET_LINE_TICKET_REGISTER_ON_PATTERN foreign key (PATTERN_ID) references TICKET_PATTERN(ID)^
alter table TICKET_LINE_TICKET_REGISTER add constraint FK_TICKET_LINE_TICKET_REGISTER_ON_ISSUE foreign key (ISSUE_ID) references TICKET_ISSUE(ID)^
alter table TICKET_LINE_TICKET_REGISTER add constraint FK_TICKET_LINE_TICKET_REGISTER_ON_INCIDENT foreign key (INCIDENT_ID) references TICKET_INCIDENT(ID)^
alter table TICKET_LINE_TICKET_REGISTER add constraint FK_TICKET_LINE_TICKET_REGISTER_ON_TITLE_DOCUMENT foreign key (TITLE_DOCUMENT_ID) references TICKET_TITLE_DOCS(ID)^
alter table TICKET_LINE_TICKET_REGISTER add constraint FK_TICKET_LINE_TICKET_REGISTER_ON_ACTIVITY foreign key (ACTIVITY_ID) references TICKET_ACTIVITY(ID)^
create index IDX_TICKET_LINE_TICKET_REGISTER_ON_TICKET on TICKET_LINE_TICKET_REGISTER (TICKET_ID)^
create index IDX_TICKET_LINE_TICKET_REGISTER_ON_PERSON on TICKET_LINE_TICKET_REGISTER (PERSON_ID)^
create index IDX_TICKET_LINE_TICKET_REGISTER_ON_PATTERN on TICKET_LINE_TICKET_REGISTER (PATTERN_ID)^
create index IDX_TICKET_LINE_TICKET_REGISTER_ON_ISSUE on TICKET_LINE_TICKET_REGISTER (ISSUE_ID)^
create index IDX_TICKET_LINE_TICKET_REGISTER_ON_INCIDENT on TICKET_LINE_TICKET_REGISTER (INCIDENT_ID)^
create index IDX_TICKET_LINE_TICKET_REGISTER_ON_TITLE_DOCUMENT on TICKET_LINE_TICKET_REGISTER (TITLE_DOCUMENT_ID)^
create index IDX_TICKET_LINE_TICKET_REGISTER_ON_ACTIVITY on TICKET_LINE_TICKET_REGISTER (ACTIVITY_ID)^
-- end TICKET_LINE_TICKET_REGISTER
-- begin TICKET_TICKET_WITHDRAWAL
alter table TICKET_TICKET_WITHDRAWAL add constraint FK_TICKET_TICKET_WITHDRAWAL_ON_RELATIVE_DOC foreign key (RELATIVE_DOC_ID) references TICKET_INCIDENT(ID)^
create index IDX_TICKET_TICKET_WITHDRAWAL_ON_RELATIVE_DOC on TICKET_TICKET_WITHDRAWAL (RELATIVE_DOC_ID)^
-- end TICKET_TICKET_WITHDRAWAL
-- begin TICKET_TICKET_ISSUE
alter table TICKET_TICKET_ISSUE add constraint FK_TICKET_TICKET_ISSUE_ON_PERSONS foreign key (PERSONS_ID) references TICKET_LINE_PERSON(ID)^
alter table TICKET_TICKET_ISSUE add constraint FK_TICKET_TICKET_ISSUE_ON_RELATIVE_DOC foreign key (RELATIVE_DOC_ID) references TICKET_INCIDENT(ID)^
create index IDX_TICKET_TICKET_ISSUE_ON_PERSONS on TICKET_TICKET_ISSUE (PERSONS_ID)^
create index IDX_TICKET_TICKET_ISSUE_ON_RELATIVE_DOC on TICKET_TICKET_ISSUE (RELATIVE_DOC_ID)^
-- end TICKET_TICKET_ISSUE
-- begin TICKET_LINE_ACITIVITY
alter table TICKET_LINE_ACITIVITY add constraint FK_TICKET_LINE_ACITIVITY_ON_ACTIVITY foreign key (ACTIVITY_ID) references TICKET_ACTIVITY(ID)^
alter table TICKET_LINE_ACITIVITY add constraint FK_TICKET_LINE_ACITIVITY_ON_RESPONSIBLE foreign key (RESPONSIBLE_ID) references TICKET_PERSON(ID)^
alter table TICKET_LINE_ACITIVITY add constraint FK_TICKET_LINE_ACITIVITY_ON_REPORTER foreign key (REPORTER_ID) references TICKET_PERSON(ID)^
alter table TICKET_LINE_ACITIVITY add constraint FK_TICKET_LINE_ACITIVITY_ON_INCIDENT foreign key (INCIDENT_ID) references TICKET_INCIDENT(ID)^
create index IDX_TICKET_LINE_ACITIVITY_ON_ACTIVITY on TICKET_LINE_ACITIVITY (ACTIVITY_ID)^
create index IDX_TICKET_LINE_ACITIVITY_ON_RESPONSIBLE on TICKET_LINE_ACITIVITY (RESPONSIBLE_ID)^
create index IDX_TICKET_LINE_ACITIVITY_ON_REPORTER on TICKET_LINE_ACITIVITY (REPORTER_ID)^
create index IDX_TICKET_LINE_ACITIVITY_ON_INCIDENT on TICKET_LINE_ACITIVITY (INCIDENT_ID)^
-- end TICKET_LINE_ACITIVITY
-- begin TICKET_LINE_SHAPE_ACTIVITY
alter table TICKET_LINE_SHAPE_ACTIVITY add constraint FK_TICKET_LINE_SHAPE_ACTIVITY_ON_ACTIVITY foreign key (ACTIVITY_ID) references TICKET_ACTIVITY(ID)^
alter table TICKET_LINE_SHAPE_ACTIVITY add constraint FK_TICKET_LINE_SHAPE_ACTIVITY_ON_ACTIVITY_PATTERN foreign key (ACTIVITY_PATTERN_ID) references TICKET_ACTIVITY_PATTERN(ID)^
create index IDX_TICKET_LINE_SHAPE_ACTIVITY_ON_ACTIVITY on TICKET_LINE_SHAPE_ACTIVITY (ACTIVITY_ID)^
create index IDX_TICKET_LINE_SHAPE_ACTIVITY_ON_ACTIVITY_PATTERN on TICKET_LINE_SHAPE_ACTIVITY (ACTIVITY_PATTERN_ID)^
-- end TICKET_LINE_SHAPE_ACTIVITY
-- begin TICKET_INCIDENT
alter table TICKET_INCIDENT add constraint FK_TICKET_INCIDENT_ON_ACTIVITY_PATTERN foreign key (ACTIVITY_PATTERN_ID) references TICKET_ACTIVITY_PATTERN(ID)^
alter table TICKET_INCIDENT add constraint FK_TICKET_INCIDENT_ON_WORK_PLACE foreign key (WORK_PLACE_ID) references TICKET_WORK_PLACE(ID)^
alter table TICKET_INCIDENT add constraint FK_TICKET_INCIDENT_ON_INITIATOR foreign key (INITIATOR_ID) references TICKET_PERSON(ID)^
alter table TICKET_INCIDENT add constraint FK_TICKET_INCIDENT_ON_VIEW foreign key (VIEW_ID) references TICKET_INCIDENT_VIEW(ID)^
alter table TICKET_INCIDENT add constraint FK_TICKET_INCIDENT_ON_OUTCOME foreign key (OUTCOME_ID) references TICKET_INCIDENT_OUTCOME(ID)^
alter table TICKET_INCIDENT add constraint FK_TICKET_INCIDENT_ON_REASON foreign key (REASON_ID) references TICKET_INCIDENT_REASON(ID)^
create index IDX_TICKET_INCIDENT_ON_ACTIVITY_PATTERN on TICKET_INCIDENT (ACTIVITY_PATTERN_ID)^
create index IDX_TICKET_INCIDENT_ON_WORK_PLACE on TICKET_INCIDENT (WORK_PLACE_ID)^
create index IDX_TICKET_INCIDENT_ON_INITIATOR on TICKET_INCIDENT (INITIATOR_ID)^
create index IDX_TICKET_INCIDENT_ON_VIEW on TICKET_INCIDENT (VIEW_ID)^
create index IDX_TICKET_INCIDENT_ON_OUTCOME on TICKET_INCIDENT (OUTCOME_ID)^
create index IDX_TICKET_INCIDENT_ON_REASON on TICKET_INCIDENT (REASON_ID)^
-- end TICKET_INCIDENT
-- begin TICKET_ACTIVITY_PATTERN
alter table TICKET_ACTIVITY_PATTERN add constraint FK_TICKET_ACTIVITY_PATTERN_ON_INCIDENT foreign key (INCIDENT_ID) references TICKET_INCIDENT(ID)^
create index IDX_TICKET_ACTIVITY_PATTERN_ON_INCIDENT on TICKET_ACTIVITY_PATTERN (INCIDENT_ID)^
-- end TICKET_ACTIVITY_PATTERN

-- begin TICKET_LINE_STRUCKED_PERSON
alter table TICKET_LINE_STRUCKED_PERSON add constraint FK_TICKET_LINE_STRUCKED_PERSON_ON_PERSON foreign key (PERSON_ID) references TICKET_PERSON(ID)^
alter table TICKET_LINE_STRUCKED_PERSON add constraint FK_TICKET_LINE_STRUCKED_PERSON_ON_DAMAGE_DEGREE foreign key (DAMAGE_DEGREE_ID) references TICKET_DAMAGE_DEGREE(ID)^
alter table TICKET_LINE_STRUCKED_PERSON add constraint FK_TICKET_LINE_STRUCKED_PERSON_ON_WORK_PLACE foreign key (WORK_PLACE_ID) references TICKET_WORK_PLACE(ID)^
alter table TICKET_LINE_STRUCKED_PERSON add constraint FK_TICKET_LINE_STRUCKED_PERSON_ON_INCIDENT foreign key (INCIDENT_ID) references TICKET_INCIDENT(ID)^
create index IDX_TICKET_LINE_STRUCKED_PERSON_ON_PERSON on TICKET_LINE_STRUCKED_PERSON (PERSON_ID)^
create index IDX_TICKET_LINE_STRUCKED_PERSON_ON_DAMAGE_DEGREE on TICKET_LINE_STRUCKED_PERSON (DAMAGE_DEGREE_ID)^
create index IDX_TICKET_LINE_STRUCKED_PERSON_ON_WORK_PLACE on TICKET_LINE_STRUCKED_PERSON (WORK_PLACE_ID)^
create index IDX_TICKET_LINE_STRUCKED_PERSON_ON_INCIDENT on TICKET_LINE_STRUCKED_PERSON (INCIDENT_ID)^
-- end TICKET_LINE_STRUCKED_PERSON
-- begin TICKET_LINE_COMMISSION_PERSON
alter table TICKET_LINE_COMMISSION_PERSON add constraint FK_TICKET_LINE_COMMISSION_PERSON_ON_PERSON foreign key (PERSON_ID) references TICKET_PERSON(ID)^
alter table TICKET_LINE_COMMISSION_PERSON add constraint FK_TICKET_LINE_COMMISSION_PERSON_ON_INCIDENT foreign key (INCIDENT_ID) references TICKET_INCIDENT(ID)^
create index IDX_TICKET_LINE_COMMISSION_PERSON_ON_PERSON on TICKET_LINE_COMMISSION_PERSON (PERSON_ID)^
create index IDX_TICKET_LINE_COMMISSION_PERSON_ON_INCIDENT on TICKET_LINE_COMMISSION_PERSON (INCIDENT_ID)^
-- end TICKET_LINE_COMMISSION_PERSON
-- begin TICKET_LINE_VIOLATOR_PERSON
alter table TICKET_LINE_VIOLATOR_PERSON add constraint FK_TICKET_LINE_VIOLATOR_PERSON_ON_PERSON foreign key (PERSON_ID) references TICKET_PERSON(ID)^
alter table TICKET_LINE_VIOLATOR_PERSON add constraint FK_TICKET_LINE_VIOLATOR_PERSON_ON_WORK_PLACE foreign key (WORK_PLACE_ID) references TICKET_WORK_PLACE(ID)^
alter table TICKET_LINE_VIOLATOR_PERSON add constraint FK_TICKET_LINE_VIOLATOR_PERSON_ON_ACTIVITY foreign key (ACTIVITY_ID) references TICKET_ACTIVITY(ID)^
alter table TICKET_LINE_VIOLATOR_PERSON add constraint FK_TICKET_LINE_VIOLATOR_PERSON_ON_INCIDENT foreign key (INCIDENT_ID) references TICKET_INCIDENT(ID)^
alter table TICKET_LINE_VIOLATOR_PERSON add constraint FK_TICKET_LINE_VIOLATOR_PERSON_ON_LAW_ARTICLE foreign key (LAW_ARTICLE_ID) references TICKET_LAW_ARTICLE(ID)^
create index IDX_TICKET_LINE_VIOLATOR_PERSON_ON_PERSON on TICKET_LINE_VIOLATOR_PERSON (PERSON_ID)^
create index IDX_TICKET_LINE_VIOLATOR_PERSON_ON_WORK_PLACE on TICKET_LINE_VIOLATOR_PERSON (WORK_PLACE_ID)^
create index IDX_TICKET_LINE_VIOLATOR_PERSON_ON_ACTIVITY on TICKET_LINE_VIOLATOR_PERSON (ACTIVITY_ID)^
create index IDX_TICKET_LINE_VIOLATOR_PERSON_ON_INCIDENT on TICKET_LINE_VIOLATOR_PERSON (INCIDENT_ID)^
create index IDX_TICKET_LINE_VIOLATOR_PERSON_ON_LAW_ARTICLE on TICKET_LINE_VIOLATOR_PERSON (LAW_ARTICLE_ID)^
-- end TICKET_LINE_VIOLATOR_PERSON
-- begin TICKET_LINE_INVOLVED_PERSON
alter table TICKET_LINE_INVOLVED_PERSON add constraint FK_TICKET_LINE_INVOLVED_PERSON_ON_PERSON foreign key (PERSON_ID) references TICKET_PERSON(ID)^
alter table TICKET_LINE_INVOLVED_PERSON add constraint FK_TICKET_LINE_INVOLVED_PERSON_ON_INCIDENT foreign key (INCIDENT_ID) references TICKET_INCIDENT(ID)^
create index IDX_TICKET_LINE_INVOLVED_PERSON_ON_PERSON on TICKET_LINE_INVOLVED_PERSON (PERSON_ID)^
create index IDX_TICKET_LINE_INVOLVED_PERSON_ON_INCIDENT on TICKET_LINE_INVOLVED_PERSON (INCIDENT_ID)^
-- end TICKET_LINE_INVOLVED_PERSON
-- begin TICKET_LINE_COMMON_ACTIVITY
alter table TICKET_LINE_COMMON_ACTIVITY add constraint FK_TICKET_LINE_COMMON_ACTIVITY_ON_INCIDENT foreign key (INCIDENT_ID) references TICKET_INCIDENT(ID)^
alter table TICKET_LINE_COMMON_ACTIVITY add constraint FK_TICKET_LINE_COMMON_ACTIVITY_ON_ACTIVITY foreign key (ACTIVITY_ID) references TICKET_ACTIVITY(ID)^
alter table TICKET_LINE_COMMON_ACTIVITY add constraint FK_TICKET_LINE_COMMON_ACTIVITY_ON_REPORTER foreign key (REPORTER_ID) references TICKET_PERSON(ID)^
alter table TICKET_LINE_COMMON_ACTIVITY add constraint FK_TICKET_LINE_COMMON_ACTIVITY_ON_RESPONSIBLE foreign key (RESPONSIBLE_ID) references TICKET_PERSON(ID)^
create index IDX_TICKET_LINE_COMMON_ACTIVITY_ON_INCIDENT on TICKET_LINE_COMMON_ACTIVITY (INCIDENT_ID)^
create index IDX_TICKET_LINE_COMMON_ACTIVITY_ON_ACTIVITY on TICKET_LINE_COMMON_ACTIVITY (ACTIVITY_ID)^
create index IDX_TICKET_LINE_COMMON_ACTIVITY_ON_REPORTER on TICKET_LINE_COMMON_ACTIVITY (REPORTER_ID)^
create index IDX_TICKET_LINE_COMMON_ACTIVITY_ON_RESPONSIBLE on TICKET_LINE_COMMON_ACTIVITY (RESPONSIBLE_ID)^
-- end TICKET_LINE_COMMON_ACTIVITY
-- begin TICKET_LINE_DOCS
alter table TICKET_LINE_DOCS add constraint FK_TICKET_LINE_DOCS_ON_INCIDENT foreign key (INCIDENT_ID) references TICKET_INCIDENT(ID)^
create index IDX_TICKET_LINE_DOCS_ON_INCIDENT on TICKET_LINE_DOCS (INCIDENT_ID)^
-- end TICKET_LINE_DOCS
