alter table TICKET_LINE_ACITIVITY add constraint FK_TICKET_LINE_ACITIVITY_ON_ACTIVITY foreign key (ACTIVITY_ID) references TICKET_ACTIVITY(ID);
alter table TICKET_LINE_ACITIVITY add constraint FK_TICKET_LINE_ACITIVITY_ON_INCIDENT foreign key (INCIDENT_ID) references TICKET_INCIDENT(ID);
create index IDX_TICKET_LINE_ACITIVITY_ON_ACTIVITY on TICKET_LINE_ACITIVITY (ACTIVITY_ID);
create index IDX_TICKET_LINE_ACITIVITY_ON_INCIDENT on TICKET_LINE_ACITIVITY (INCIDENT_ID);
