alter table TICKET_LINE_SHAPE add constraint FK_TICKET_LINE_SHAPE_ON_PATTERN foreign key (PATTERN_ID) references TICKET_PATTERN(ID);
create index IDX_TICKET_LINE_SHAPE_ON_PATTERN on TICKET_LINE_SHAPE (PATTERN_ID);
