alter table TICKET_LINE_PERSON add constraint FK_TICKET_LINE_PERSON_ON_TICKET_ISSUE foreign key (TICKET_ISSUE_ID) references TICKET_TICKET_ISSUE(ID);
create index IDX_TICKET_LINE_PERSON_ON_TICKET_ISSUE on TICKET_LINE_PERSON (TICKET_ISSUE_ID);
