alter table TICKET_TICKET_ISSUE add constraint FK_TICKET_TICKET_ISSUE_ON_RELATIVE_DOC foreign key (RELATIVE_DOC_ID) references TICKET_INCIDENT(ID);
create index IDX_TICKET_TICKET_ISSUE_ON_RELATIVE_DOC on TICKET_TICKET_ISSUE (RELATIVE_DOC_ID);
