alter table TICKET_LINE_TICKET add constraint FK_TICKET_LINE_TICKET_ON_TICKET foreign key (TICKET_ID) references TICKET_TICKET(ID);
alter table TICKET_LINE_TICKET add constraint FK_TICKET_LINE_TICKET_ON_LINE_PERSON foreign key (LINE_PERSON_ID) references TICKET_LINE_PERSON(ID);
create unique index IDX_TICKET_LINE_TICKET_UNIQ_QUANTITY on TICKET_LINE_TICKET (QUANTITY) ;
create index IDX_TICKET_LINE_TICKET_ON_TICKET on TICKET_LINE_TICKET (TICKET_ID);
create index IDX_TICKET_LINE_TICKET_ON_LINE_PERSON on TICKET_LINE_TICKET (LINE_PERSON_ID);
