alter table TICKET_INCIDENT add constraint FK_TICKET_INCIDENT_ON_INITIATOR foreign key (INITIATOR_ID) references TICKET_PERSON(ID);
create index IDX_TICKET_INCIDENT_ON_INITIATOR on TICKET_INCIDENT (INITIATOR_ID);
