alter table TICKET_LINE_ACITIVITY add constraint FK_TICKET_LINE_ACITIVITY_ON_REPORTER foreign key (REPORTER_ID) references TICKET_PERSON(ID);
create index IDX_TICKET_LINE_ACITIVITY_ON_REPORTER on TICKET_LINE_ACITIVITY (REPORTER_ID);
