alter table TICKET_INCIDENT add constraint FK_TICKET_INCIDENT_ON_OUTCOME foreign key (OUTCOME_ID) references TICKET_INCIDENT_OUTCOME(ID);
create index IDX_TICKET_INCIDENT_ON_OUTCOME on TICKET_INCIDENT (OUTCOME_ID);
