alter table TICKET_LINE_ACITIVITY add constraint FK_TICKET_LINE_ACITIVITY_ON_INCIDENT foreign key (INCIDENT_ID) references TICKET_INCIDENT(ID);
create index IDX_TICKET_LINE_ACITIVITY_ON_INCIDENT on TICKET_LINE_ACITIVITY (INCIDENT_ID);
