alter table TICKET_INCIDENT add constraint FK_TICKET_INCIDENT_ON_WORK_PLACE foreign key (WORK_PLACE_ID) references TICKET_WORK_PLACE(ID);
create index IDX_TICKET_INCIDENT_ON_WORK_PLACE on TICKET_INCIDENT (WORK_PLACE_ID);
