alter table TICKET_INCIDENT add constraint FK_TICKET_INCIDENT_ON_REASON foreign key (REASON_ID) references TICKET_INCIDENT_REASON(ID);
create index IDX_TICKET_INCIDENT_ON_REASON on TICKET_INCIDENT (REASON_ID);
