alter table TICKET_LINE_DOCS add constraint FK_TICKET_LINE_DOCS_ON_INCIDENT foreign key (INCIDENT_ID) references TICKET_INCIDENT(ID);
create index IDX_TICKET_LINE_DOCS_ON_INCIDENT on TICKET_LINE_DOCS (INCIDENT_ID);
