alter table TICKET_ACTIVITY_PATTERN add constraint FK_TICKET_ACTIVITY_PATTERN_ON_INCIDENT foreign key (INCIDENT_ID) references TICKET_INCIDENT(ID);
create index IDX_TICKET_ACTIVITY_PATTERN_ON_INCIDENT on TICKET_ACTIVITY_PATTERN (INCIDENT_ID);
