alter table TICKET_ACTIVITY add constraint FK_TICKET_ACTIVITY_ON_INCIDENT foreign key (INCIDENT_ID) references TICKET_INCIDENT(ID);
create index IDX_TICKET_ACTIVITY_ON_INCIDENT on TICKET_ACTIVITY (INCIDENT_ID);
