alter table TICKET_INCIDENT add constraint FK_TICKET_INCIDENT_ON_COMMON_INFO foreign key (COMMON_INFO_ID) references TICKET_INCIDENT_COMMON_INFO(ID);
create index IDX_TICKET_INCIDENT_ON_COMMON_INFO on TICKET_INCIDENT (COMMON_INFO_ID);
